# Generated by Django 2.0.1 on 2018-01-11 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=20)),
                ('remainder', models.DateTimeField(default=None)),
                ('is_pinned', models.BooleanField(default=False)),
                ('color', models.CharField(default=None, max_length=20)),
                ('collaborate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collaborated_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
