# Generated by Django 2.0.1 on 2018-01-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20180111_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='is_pinned',
            field=models.NullBooleanField(default=None),
        ),
    ]
