# Generated by Django 2.0.1 on 2018-01-11 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180111_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='collaborate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborated_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
