# Generated by Django 2.0.1 on 2018-01-12 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20180111_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='remainder1',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 10, 19, 50, 545381)),
        ),
    ]
