# Generated by Django 2.0.1 on 2018-01-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_notes_remainder1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='remainder1',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
