# Generated by Django 2.0.1 on 2018-01-12 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20180112_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='remainder1',
        ),
        migrations.AddField(
            model_name='notes',
            name='now',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 11, 30, 25, 893757)),
        ),
    ]
